### ISSUE TITLE
Mouse cursor stuck on the side of the screen

### ISSUE THREAD

**Issue by Thomot512** [systemofapwne/leetmouse#4] opened 2021-05-09 06:13 UTC
On 5.12.1-arch1-1, I ran into an issue where the mouse cursor is stuck on the side of the screen until I reboot or uninstall (or re-install) leetmouse.
Step to reproduce:

1.  Go to a streaming website such as Youtube;
2. start a video (not all but most video have this issue, [here'](https://www.youtube.com/watch?v=tjT9gt0dArQ)s a link to one that has this issue);
3. wait for 10 to 15s without moving the mouse;

Expected behaviour:
The mouse cursor should become invisible to avoid disturbing while watching the video.
Behaviour:
The mouse cursor snaps to the left of the screen and can yet only be moved vertically. Behaviour continues until the computer is rebooted or the leetmouse driver is uninstalled.

Info System:
OS: RebornOS Linux x86_64
Kernel: 5.12.1-arch1-1
DE: Plasma
WM: KWin
CPU: Intel i9-7920X (24) @ 4.300GHz
GPU: NVIDIA TITAN X
GPU: NVIDIA TITAN X
Memory: 10556MiB / 31789MiB
Mouse: Cooler Master MM710 ; Swiftpoint Tracer
Internet Browser: Brave Version 1.24.82 Chromium: 90.0.4430.93 (Official Build) (64-bit)

**Comment by systemofapwne** [comment] 2021-05-15 16:18
I noticed this too some weeks ago. The fix should be in the testing-branch. Please give that a try. If you do not have this issue anymore, I will merge testing into master.

**Comment by Thomot512** [comment] 2021-05-15 20:06
With the testing branch, the youtube video seems to not trigger the issue anymore, but the sps tutorial video still triggers the issue.
(It is not happening if I play the video in full screen)

**Comment by systemofapwne** [comment] 2021-05-15 20:16
Oh, that's a bummer. I need to check now, why this happens. Unfortunately, debugging this might not to be so straight forward, since triggering this seems to be system specific and depends on the situation (like playing a video). For me, it was solved with the latest code in testing :/

For now, I have seen this happening whenever a float is pushed to a call stack. That's why I rather use pass-by-pointer and inlining, where I can. However even then, floating point arithmetic seems to get screwed up sometimes, which then made me to add [this ugly check/workaround](https://github.com/systemofapwne/leetmouse/blob/234425fcdaf3a708b6da2f67ab6874dbed752b1c/driver/accel.c#L127). Apparently, it is not enough...

**Comment by systemofapwne** [comment] 2021-05-16 12:11
Please give the latest commit in testing a try. I now explicitly force code-inlining now, where it matters (read about more here, why this matters: https://yarchive.net/comp/linux/kernel_fp.html). I expect this to be the reason, why it failed at your end. However, I added an additional "is_valid" check, to test if a float is either NaN, positive infinity or negative infinity.
Lets hope, that this bug is now fixed!

**Comment by systemofapwne** [comment] 2021-05-16 13:32
When disassembling the module, I noticed, it still does not always inline all the code. It looks like, the always_inline attribute only is working during compilation, not when linking the different objects together. I am now looking for how to force it even here.
Alternatively, it would need me to mege all c files and compile then, which I would like to avoid. I keep you updated.

**Comment by Thomot512** [comment] 2021-05-16 15:44
The issue is still present in the testing branch.

**Comment by systemofapwne** [comment] 2021-05-16 15:45
Alright. I will quickly push another commit soon, where inlining definitely is working. Give me a few minutes. It would be nice if you then could give feedback on a short notice :)

**Comment by systemofapwne** [comment] 2021-05-16 15:58
Latest commit is pushed to testing. All floating point operation is now properly inlined between kernel_fpu_begin() and kernel_fpu_end() -> No more function calls.
I hope, this fixed the problems. I really would like to know, if this fixes your problems.

If now, please do the following:

run ```modinfo leetmouse``` to find the path to the module

It should return something like
```
filename:       /lib/modules/5.4.116-1-MANJARO/kernel/drivers/hid/leetmouse.ko.xz
license:        GPL
description:    USB HID mouse driver with acceleration (LEETMOUSE)
author:         Vojtech Pavlik <vojtech@ucw.cz>
author:         Klaus Zipfel <klaus (at) zipfel (dot) family>
author:         Christopher Williams <chilliams (at) gmail (dot) com>
srcversion:     5E3B65904A3D936A773B113
alias:          usb:v*p*d*dc*dsc*dp*ic03isc01ip02in*
depends:        hid
retpoline:      Y
name:           leetmouse
vermagic:       5.4.116-1-MANJARO SMP preempt mod_unload modversions 
parm:           debug:byte
parm:           no_bind:This will disable binding to this driver via 'leetmouse_bind' by udev. (byte)
parm:           update:Triggers an update of the acceleration parameters below (byte)
parm:           PreScaleX:Prescale X-Axis before applying acceleration. (charp)
parm:           PreScaleY:Prescale Y-Axis before applying acceleration. (charp)
parm:           SpeedCap:Limit the maximum pointer speed before applying acceleration. (charp)
parm:           Sensitivity:Mouse base sensitivity. (charp)
parm:           Acceleration:Mouse acceleration sensitivity. (charp)
parm:           SensitivityCap:Cap maximum sensitivity. (charp)
parm:           Offset:Mouse base sensitivity. (charp)
parm:           PostScaleX:Postscale X-Axis after applying acceleration. (charp)
parm:           PostScaleY:Postscale >-Axis after applying acceleration. (charp)
parm:           ScrollsPerTick:Amount of lines to scroll per scroll-wheel tick. (charp)
```

Please upload the kernel module at ``/lib/modules/5.4.116-1-MANJARO/kernel/drivers/hid/leetmouse.ko.xz`` then.

**Comment by systemofapwne** [comment] 2021-05-16 21:20
While thinking the bug was fixed with inlining, I was browsing the web, until [this video](https://www.ginx.tv/en/cs-go/cs-go-trusted-mode-how-to-enable-third-party-software) triggered the bug for me again :(

While debugging the driver, I think I am now confident to have found the cause: [This assignment](https://github.com/systemofapwne/leetmouse/blob/5737b6e1ae1d1d2b491b1b21ad8b88e464b7a9ca/driver/accel.c#L95) is outside the k[ernel_fpu_begin()](https://github.com/systemofapwne/leetmouse/blob/5737b6e1ae1d1d2b491b1b21ad8b88e464b7a9ca/driver/accel.c#L121) and [kernel_fpu_end()](https://github.com/systemofapwne/leetmouse/blob/5737b6e1ae1d1d2b491b1b21ad8b88e464b7a9ca/driver/accel.c#L222) statement. I completely missed that...

This is now fixed and will be shortly available upstream. Please report back, once I have pushed the (supposed to be final) bugfix.

**Comment by systemofapwne** [comment] 2021-05-16 22:03
Fix is now upstream in testing. Please check it out and report back :)

**Comment by Thomot512** [comment] 2021-05-17 17:47
I tested a few videos including the sps one, and the last one you posted, and I could not trigger this issue anymore. I will test further in the following days.

**Closed** 2021-05-17 23:07 UTC
Labels: bug

**Comment by systemofapwne** [comment] 2021-05-17 23:11
I am pretty confident, that this is now fixed. Feel free to re-open anytime again.
I also have merged testing into master.
